# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a34c3e4d1c0d7d4648035c7a5b18a77766f764257861af0ad882fc893d9d40c847730adfc3e1308bafc12282f9344e005c1c20ee0a8a0ad878d09d62f8604b94

test:
  secret_key_base: a5a8433231aea96cdf030040571c4836827b7df2f5fe8852c6958c3fdf15e8a7edd15a57211dff092f43025976479c4b454124acc38b11159a17ace09f3ebe6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
